---
title: "ELSA Plots 📈"
date: "2024-10-25"
format: revealjs
---

## Gait speed 
### (+ `gtspd_raw.mean`)


```{r include=FALSE}
library(tidyverse)
library(xlsx)
library(patchwork)
theme_set(theme_minimal())
level_labels <- c(
        "highest wealth quintile",
        "higher wealth quintile",
        "middle wealth quintile",
        "lower wealth quintile",
        "lowest wealth quintile"
      )

plot <- function(data, xaxis, level_labels, labx, laby){
  
  data |>
  arrange(X_margin) |>
  mutate(Wealth.quintile = factor(
    Wealth.quintile,
    levels =
      level_labels
  )) %>%
  ggplot(aes(x = {{xaxis}},
          )) +
      geom_line(aes(color = Wealth.quintile, 
             y = X_margin), linewidth = 0.5) +
  geom_ribbon(aes(ymin = X_ci_lb, ymax = X_ci_ub, fill = Wealth.quintile),
              alpha = 0.1) +
  scale_fill_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  scale_color_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  theme_bw() +
  labs(x = labx,
       y = laby,
       fill = "Wealth quintile",
       color = "Wealth quintile") 

}

plot90 <- function(data, xaxis, level_labels, labx, laby){
  
  data |>
  arrange(X_margin) |>
  filter(Age < 90) |> 
  mutate(Wealth.quintile = factor(
    Wealth.quintile,
    levels =
      level_labels
  )) %>%
  ggplot(aes(x = {{xaxis}},
          )) +
      geom_line(aes(color = Wealth.quintile, 
             y = X_margin), linewidth = 0.5) +
  # geom_point(aes(color = Wealth.quintile,
  #                y = gtspd_raw.mean), size = 1) +
  geom_ribbon(aes(ymin = X_ci_lb, ymax = X_ci_ub, fill = Wealth.quintile),
              alpha = 0.1) +
  scale_fill_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  scale_color_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  theme_bw() +
  labs(x = labx,
       y = laby,
       fill = "Wealth quintile",
       color = "Wealth quintile") 
}

```



```{r, echo=FALSE}
gaitspeedovertime <- read.xlsx(here::here("data","data_21_10_2024.xlsx"), sheetIndex = 1)
gaitspeedwithage <- read.xlsx(here::here("data","data_21_10_2024.xlsx"), sheetIndex = 2)

gaitspeedage2 <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 1)
fvcwithage <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 2)
gripwithage <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 3)
chairrisewithage <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 4)
selfratedhearing <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 5)
selfratedeyesight <- read.xlsx(here::here("data","data_22_10_2024.xlsx"), sheetIndex = 6)

```



```{r echo=FALSE}
p1 = gaitspeedovertime |>
  arrange(X_margin) |>
  mutate(Wealth.quintile = factor(
    Wealth.quintile,
    levels =
      c(
        "highest wealth quintile",
        "higher wealth quintile",
        "middle wealth quintile",
        "lower wealth quintile",
        "lowest wealth quintile"
      )
  )) %>%
  ggplot(aes(x = Years)) +
    geom_line(aes(color = Wealth.quintile, 
             y = X_margin), linewidth = 0.5) +
  geom_point(aes(color = Wealth.quintile,
                 y = gtspd_raw.mean), size = 1) +
  geom_ribbon(aes(ymin = X_ci_lb, ymax = X_ci_ub, fill = Wealth.quintile),
              alpha = 0.1) +
  scale_fill_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  scale_color_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  theme_bw() +
  labs(x = "Years",
       y = "Gait Speed Over Time, m/s",
       fill = "Wealth quintile",
       color = "Wealth quintile") +
  theme(legend.position = "none")

p2 = gaitspeedwithage |>
  arrange(X_margin) |>
  mutate(Wealth.quintile = factor(
    Wealth.quintile,
    levels =
      c(
        "highest wealth quintile",
        "higher wealth quintile",
        "middle wealth quintile",
        "lower wealth quintile",
        "lowest wealth quintile"
      )
  )) %>%
  ggplot(aes(x = Age,
          )) +
      geom_line(aes(color = Wealth.quintile, 
             y = X_margin), linewidth = 0.5) +
  geom_point(aes(color = Wealth.quintile,
                 y = gtspd_raw.mean), size = 1) +
  geom_ribbon(aes(ymin = X_ci_lb, ymax = X_ci_ub, fill = Wealth.quintile),
              alpha = 0.1) +
  scale_fill_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  scale_color_discrete(  
      labels = c("higest", "higher", "middle", "lower", "lowest")) +
  theme_bw() +
  labs(x = "Age",
       y = "Gait Speed Over Time, m/s",
       fill = "Wealth quintile",
       color = "Wealth quintile") 
  
p1 + p2
```


---

## Gait speed

```{r}
p3 = plot(data = gaitspeedage2, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Gait speed (m/s)") +
  theme(legend.position = "none")

p4 = plot90(data = gaitspeedage2, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Gait speed (m/s)")

p3 + p4
```


---

## FVC (liters)

```{r}
p5 = plot(data = fvcwithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "FVC (liters)") +
  theme(legend.position = "none")

p6 = plot90(data = fvcwithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "FVC (liters)")

p5 + p6
```

---

## Grip with Age

```{r}
p7 = plot(data = gripwithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Grip Strength (kg)")  +
  theme(legend.position = "none")

p8 = plot90(data = gripwithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Grip Strength (kg)")

p7 + p8
```

---

## Chair rise

```{r}
p9 = plot(data = chairrisewithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "5 chair rises (log time in seconds)") +
  theme(legend.position = "none")

p10 = plot90(data = chairrisewithage, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "5 chair rises (log time in seconds)")

p9 + p10
```


---

## Self-rated hearing

```{r}
p11 = plot(data = selfratedhearing, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Self-rated Hearing Loss") +
  theme(legend.position = "none")

p12 = plot90(data = selfratedhearing, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Self-rated Hearing Loss")
  
p11 + p12
```


---

## Self-rated eyesight

```{r}
p13 = plot(data = selfratedeyesight, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Self-Rated Visual Impairment") 
#+
 # theme(legend.position = "none")

p14 = plot90(data = selfratedeyesight, 
     xaxis = Age,
     level_labels = level_labels,
     labx = "Age",
     laby = "Self-Rated Visual Impairment")
  
p13 + p14
```

---

```{r}

a = p3 + labs(tag = "A") 

b = p5 + labs(tag = "B") 

c = p7 + labs(tag = "C") 

d = p9 + labs(tag = "D") 

e = p11 + labs(tag = "E") 

f = p13 + labs(tag = "F") 

a + b + c + d + e + f +
  plot_layout(ncol = 3)


```

